// ── Sample movies (used if no file is uploaded) ──────────────────────────────
export const SAMPLE_MOVIES = [
  // ----------- ENGLISH -----------
  "The Dark Knight","Inception","Interstellar","The Matrix","Forrest Gump",
  "The Godfather","Pulp Fiction","The Shawshank Redemption","Fight Club",
  "Goodfellas","The Silence of the Lambs","Schindler's List","The Lion King",
  "Home Alone","Die Hard","Jurassic Park","Titanic","Avatar",
  "The Avengers","Iron Man","Spider-Man","Batman Begins",
  "Man of Steel","Wonder Woman","Black Panther","Doctor Strange",
  "Thor","Captain America","Gladiator","Braveheart","The Prestige",
  "Memento","Dunkirk","Oppenheimer","Whiplash","La La Land",
  "The Social Network","The Wolf of Wall Street","Shutter Island",
  "The Departed","Se7en","Zodiac","Gone Girl","The Green Mile",
  "Saving Private Ryan","1917","Mad Max: Fury Road","The Revenant",
  "Django Unchained","Inglourious Basterds","The Truman Show",
  "Dead Poets Society","A Beautiful Mind","Good Will Hunting",
  "Bohemian Rhapsody","The King's Speech","Slumdog Millionaire",
  "Life of Pi","Cast Away","The Martian","Gravity","Her",
  "Ex Machina","Blade Runner","Arrival","John Wick",
  "Mission: Impossible","Top Gun","Rocky","The Exorcist",
  "Get Out","A Quiet Place","It","The Conjuring",
  "The Sixth Sense","Unbreakable","Split","Toy Story",
  "Finding Nemo","Up","Coco","Inside Out","Ratatouille",
  "Cars","Frozen","Moana","Zootopia",

  // ----------- HINDI -----------
  "Sholay","Deewar","Zanjeer","Don","Amar Akbar Anthony",
  "Muqaddar Ka Sikandar","Trishul","Kaala Patthar","Silsila",
  "Kabhi Kabhie","Namak Halaal","Sharaabi","Coolie","Agneepath",
  "Hum","Khuda Gawah","Baazigar","Darr","Karan Arjun",
  "Dilwale Dulhania Le Jayenge","Kuch Kuch Hota Hai",
  "Kabhi Khushi Kabhie Gham","Kal Ho Naa Ho","Veer-Zaara",
  "My Name Is Khan","Dil Se","Rangeela","Lagaan","Swades",
  "Rang De Basanti","Taare Zameen Par","Ghajini","3 Idiots",
  "PK","Dangal","Secret Superstar","Andaz Apna Apna",
  "Hum Aapke Hain Koun","Hum Saath Saath Hain","Biwi No.1",
  "Judwaa","Kick","Wanted","Dabangg","Bajrangi Bhaijaan",
  "Ek Tha Tiger","Sultan","Tubelight","War","Pathaan",
  "Jawan","Raees","Chennai Express","Happy New Year",
  "Om Shanti Om","Main Hoon Na","Baadshah","Yes Boss",
  "Border","Kesari","Shershaah","Uri: The Surgical Strike",
  "Raazi","Baby","Special 26","A Wednesday","Drishyam",
  "Badhaai Ho","Bala","Stree","Peepli Live","Article 15",
  "Pink","Thappad","Piku","Queen","Tanu Weds Manu",
  "Cocktail","Love Aaj Kal","Tamasha","Rockstar","Barfi",
  "Ae Dil Hai Mushkil","Yeh Jawaani Hai Deewani",
  "Wake Up Sid","Kapoor & Sons","Dear Zindagi",
  "English Vinglish","Chandni","Lamhe","Dil To Pagal Hai",
  "Mohabbatein","Devdas","Black","Saawariya","Guzaarish",
  "Padmaavat","Bajirao Mastani","Ram-Leela","Gully Boy",
  "83","Chak De India","Dil Chahta Hai",
  "Zindagi Na Milegi Dobara","Rock On","Udaan",
  "Masaan","Newton","Haider","Omkara","Maqbool",
  "Company","Satya","Sarkar","Hera Pheri",
  "Welcome","Hungama","Mujhse Shaadi Karogi","No Entry",
  "Partner","Ready","Bodyguard","Singh Is Kinng",
  "Namastey London","Toilet: Ek Prem Katha","Pad Man",
  "Airlift","Rustom","Mission Mangal",
  "Krrish","Koi... Mil Gaya","Ra.One","Robot",

  // ----------- NEPALI -----------
  "Kusume Rumal","Darpan Chhaya","Prem Pinda","Numafung",
  "Kagbeni","Loot","Talakjung vs Tulke",
  "Kabaddi","Jatra","Chhakka Panja",
  "Hostel","Pashupati Prasad","Love Love Love",
  "Dreams","A Mero Hajur","Chapali Height",
  "Bir Bikram","Shatru Gate","Gopi","Nai Nabhannu La",
  "Resham Filili","Selfie King","Prasad",
  "Mero Euta Saathi Chha","Saayad","Soongava","Uma",
  "Sanguro","The Black Hen","Seto Surya",
  "Highway","Kalo Pothi","Sano Sansar",
  "November Rain","Classic","Jerry","Kri",
  "Captain","Password","Intu Mintu Londonma",
  "Romeo & Muna","Muna Madan","Basanti",
  "Jaya Shiva Shankar","Dui Rupaiyan","How Funny",
  "Timi Sanga","Lily Bily","Gangster Blues",
  "Mr. Jholay","Aama","Bulbul","Dhanapati",
  "Mahapurush","Fulbari","Samjhana Birsana",
  "Manjari","Ghar","Pardeshi","Prem Geet"
];